name: "Build"
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
       os: [ ubuntu-latest, macos-latest ]
       # we need this to map platform names as used by github to
       # the attribute names defined in release.nix
       include:
         - os: ubuntu-latest
           os_attr: linux
         - os: macos-latest
           os_attr: darwin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: hevm
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: run cabal check
        run: nix-shell --pure --command "cabal check --verbose=3"
      - name: build hevm
        run: nix build .#withTests -L
      - name: Upload artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: hevm-x86_64-linux
          path: result/bin/hevm
      - name: run rpc tests
        run: nix-shell --pure --command "cabal run rpc-tests"
      - name: run ethereum tests
        run: nix-shell --command "cabal run ethereum-tests"
  build-windows:
    name: build (windows-latest)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          path-type: inherit
          update: true
          install: >-
            base-devel
            gmp-devel
            openssl-devel
            git
            unzip
          pacboy: >-
            cmake:p
            ninja:p
            gcc:p
            autotools:p
            gmp:p
            openssl:p
      - uses: haskell/actions/setup@v2
        id: cabal
        with:
          ghc-version: '9.2'
      - run: |
          cd network
          autoreconf -i
      - name: run cabal check
        run: cabal check --verbose=3
      - name: build and install dependencies
        run: |
          echo "::group::Installing libsecp256k1"
          ./.github/scripts/install-libsecp256k1.sh
          echo "::endgroup::"
          echo "::group::Installing libff"
          ./.github/scripts/install-libff.sh
          echo "::endgroup::"
      - name: build hevm library
        run: |
          cabal build --extra-include-dirs="$HOME/.local/include" --extra-lib-dirs="$HOME/.local/lib"
